name: 🛠️ Build Error
description: Report a build error for this project
title: "[BUILD ERROR] <title>"
labels: ["Build ERR"]
body:
- type: checkboxes
  id: prev_issue
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the build error you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description of the Build Error
    description: Provide a clear and concise description of what the build error is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Provide a clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Describe the steps you took to trigger the build error. Include any commands you executed or files you modified.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment Information
    description: |
      Provide details about your environment.
      Example:
        - Operating System version: Ubuntu 20.04
        - GCC version: 9.3.0
        - Pybind version: 2.8.1
        - CUDA version: 11.4
        - NVIDIA NCCL CU11 version: 2.14.3
        - CMake version: 3.21.2
        - Pip version: 22.0.0
    value: |
        - Operating System version:
        - GCC version:
        - Pybind version:
        - CUDA version:
        - NVIDIA NCCL CU11 version:
        - CMake version:
        - Pip version:
    render: markdown
  validations:
    required: true
- type: dropdown
  attributes:
    label: Installation Method
    description: Please indicate if the error occurred during source code installation or when using the pip install .whl method.
    options:
      - Source Code Installation
      - Pip Install .whl Method
  validations:
    required: true
- type: textarea
  attributes:
    label: Full Error Traceback
    description: Provide the complete error traceback.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Provide any other relevant context or information about the problem here.
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  id: confirm
  attributes:
    label: Confirmation
    description: Please confirm that you have reviewed all of the above requirements and verified the information provided before submitting this report.
    options:
      - label: I have reviewed and verified all the information provided in this report.
  validations:
    required: true

